live_config_reload = true

[colors.normal]
black = "0x2d2d2d"
blue = "0x6699cc"
cyan = "0x0cffe1"
green = "0x99cc99"
magenta = "0xff217c"
red = "0xff3334"
white = "0xd3d0c8"
yellow = "0xfee484"

[colors.primary]
background = "0x2d2d2d"
#cursor = "0xd3d0c8"
foreground = "0xd3d0c8"
#text = "0x2d2d2d"

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[scrolling]
history = 10000

[window]
opacity = 0.8

[window.padding]
x = 5
y = 5
