[colors.primary]
background = '#0f141a'
foreground = '#dfe2eb'

[colors.selection]
text = '#dfe2eb'
background = '#434b00'

[colors.cursor]
text = '#0f141a'
cursor = '#c2ce72'

[colors.normal]
black   = '#0f141a'
red     = '#ec7c6a'
green   = '#71ce67'
yellow  = '#ffea72'
blue    = '#b6c35a'
magenta = '#555f11'
cyan    = '#c2ce72'
white   = '#d6d8cb'

[colors.bright]
black   = '#84857b'
red     = '#ffac9f'
green   = '#a9f7a0'
yellow  = '#fff1a5'
blue    = '#d7e28c'
magenta = '#f4ffaf'
cyan    = '#f8ffcb'
white   = '#fefff8'
