#!/usr/bin/env zsh
# Source: https://github.com/ThePrimeagen/.dotfiles/blob/master/clean-env
# I am using zsh instead of bash.  I was having some troubles using bash with
# arrays.  Didn't want to investigate, so I just did zsh
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "Removing $folder"
    stow -d $DOTFILES/configs -t $HOME -D $folder
done
