#!/usr/bin/env zsh
# Source: https://github.com/ThePrimeagen/.dotfiles/blob/master/install
# I am using zsh instead of bash.  I was having some troubles using bash with
# arrays.  Didn't want to investigate, so I just did zsh
# The packages are in configs/; -t is needed because stow's default target is
# the parent of the stow directory.
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    stow -d $DOTFILES/configs -t $HOME -D $folder
    stow -d $DOTFILES/configs -t $HOME $folder
done
